<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="4" passed="1">
  <reporter-output>
    <line>
      <![CDATA[/Users/wangxun/Documents/workspace/test/testReport/直达车web版/20151203-181116-606/failScreen/20151203-181201-023_test010addCity.png]]>
    </line>
    <line>
      <![CDATA[<img src="..//Users/wangxun/Documents/workspace/test/testReport/直达车web版/20151203-181116-606/failScreen/20151203-181201-023_test010addCity.png"/>]]>
    </line>
    <line>
      <![CDATA[/Users/wangxun/Documents/workspace/test/testReport/直达车web版/20151203-181116-606/failScreen/20151203-181208-959_test010addCity.png]]>
    </line>
    <line>
      <![CDATA[<img src="..//Users/wangxun/Documents/workspace/test/testReport/直达车web版/20151203-181116-606/failScreen/20151203-181208-959_test010addCity.png"/>]]>
    </line>
    <line>
      <![CDATA[/Users/wangxun/Documents/workspace/test/testReport/直达车web版/20151203-181116-606/failScreen/20151203-181217-134_test010addCity.png]]>
    </line>
    <line>
      <![CDATA[<img src="..//Users/wangxun/Documents/workspace/test/testReport/直达车web版/20151203-181116-606/failScreen/20151203-181217-134_test010addCity.png"/>]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="64933" started-at="2015-12-03T10:11:16Z" finished-at="2015-12-03T10:12:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="64933" started-at="2015-12-03T10:11:16Z" finished-at="2015-12-03T10:12:21Z">
      <class name="projects.ticket.testCases.ticketWeb.qiChe">
        <test-method status="PASS" signature="setUp()[pri:0, instance:projects.ticket.testCases.ticketWeb.qiChe@59a6e353]" name="setUp" is-config="true" duration-ms="6916" started-at="2015-12-03T18:11:16Z" finished-at="2015-12-03T18:11:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="test001enterAddCityPage()[pri:0, instance:projects.ticket.testCases.ticketWeb.qiChe@59a6e353]" name="test001enterAddCityPage" duration-ms="13763" started-at="2015-12-03T18:11:23Z" finished-at="2015-12-03T18:11:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test001enterAddCityPage -->
        <test-method status="FAIL" signature="test010addCity(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:projects.ticket.testCases.ticketWeb.qiChe@59a6e353]" name="test010addCity" duration-ms="19741" started-at="2015-12-03T18:11:37Z" data-provider="addCity" finished-at="2015-12-03T18:11:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[咸宁]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[XN]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[是]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[111]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 111
	at org.testng.Assert.fail(Assert.java:94)
	at test.autotest.core.UI.assertFail(UI.java:113)
	at projects.ticket.testCases.ticketWeb.qiChe.test010addCity(qiChe.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[/Users/wangxun/Documents/workspace/test/testReport/直达车web版/20151203-181116-606/failScreen/20151203-181201-023_test010addCity.png]]>
            </line>
            <line>
              <![CDATA[<img src="..//Users/wangxun/Documents/workspace/test/testReport/直达车web版/20151203-181116-606/failScreen/20151203-181201-023_test010addCity.png"/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- test010addCity -->
        <test-method status="FAIL" signature="test010addCity(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:projects.ticket.testCases.ticketWeb.qiChe@59a6e353]" name="test010addCity" duration-ms="4446" started-at="2015-12-03T18:12:01Z" data-provider="addCity" finished-at="2015-12-03T18:12:05Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[武汉]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[WH]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[是]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[111]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 111
	at org.testng.Assert.fail(Assert.java:94)
	at test.autotest.core.UI.assertFail(UI.java:113)
	at projects.ticket.testCases.ticketWeb.qiChe.test010addCity(qiChe.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[/Users/wangxun/Documents/workspace/test/testReport/直达车web版/20151203-181116-606/failScreen/20151203-181208-959_test010addCity.png]]>
            </line>
            <line>
              <![CDATA[<img src="..//Users/wangxun/Documents/workspace/test/testReport/直达车web版/20151203-181116-606/failScreen/20151203-181208-959_test010addCity.png"/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- test010addCity -->
        <test-method status="FAIL" signature="test010addCity(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:projects.ticket.testCases.ticketWeb.qiChe@59a6e353]" name="test010addCity" duration-ms="2272" started-at="2015-12-03T18:12:08Z" data-provider="addCity" finished-at="2015-12-03T18:12:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[深圳]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[SZ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[是]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[111]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: 111
	at org.testng.Assert.fail(Assert.java:94)
	at test.autotest.core.UI.assertFail(UI.java:113)
	at projects.ticket.testCases.ticketWeb.qiChe.test010addCity(qiChe.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[/Users/wangxun/Documents/workspace/test/testReport/直达车web版/20151203-181116-606/failScreen/20151203-181217-134_test010addCity.png]]>
            </line>
            <line>
              <![CDATA[<img src="..//Users/wangxun/Documents/workspace/test/testReport/直达车web版/20151203-181116-606/failScreen/20151203-181217-134_test010addCity.png"/>]]>
            </line>
          </reporter-output>
        </test-method> <!-- test010addCity -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:projects.ticket.testCases.ticketWeb.qiChe@59a6e353]" name="tearDown" is-config="true" duration-ms="3266" started-at="2015-12-03T18:12:17Z" finished-at="2015-12-03T18:12:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- projects.ticket.testCases.ticketWeb.qiChe -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
